config/routes.rb
Rails.application.routes.draw do
  root to: 'books#search'
  get 'search_books', to: 'books#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def search
    if params[:query].present?
      client = OpenLibrary::Client.new
      @results = client.search(params[:query])['docs']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/search.html.erb
<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-6">Search for books</h1>

  <%= form_tag(search_books_path, method: :get, class: 'flex mb-6') do %>
    <%= label_tag :query, 'Search query:', class: 'mr-2 self-center' %>
    <%= text_field_tag :query, params[:query], class: 'border border-gray-300 rounded-md px-2 py-1 mr-2 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent' %>
    <%= submit_tag 'Search', class: 'bg-blue-600 text-white px-4 py-1 rounded-md' %>
  <% end %>

  <% if @results.present? %>
    <table class="w-full border-collapse">
      <thead>
        <tr class="bg-gray-200">
          <th class="border border-gray-300 px-4 py-2 font-semibold">Title</th>
          <th class="border border-gray-300 px-4 py-2 font-semibold">Author</th>
        </tr>
      </thead>
      <tbody>
        <% @results.each_with_index do |result, index| %>
          <tr class="<%= index.odd? ? 'bg-gray-100' : '' %>">
            <td class="border border-gray-300 px-4 py-2"><%= result['title'] %></td>
            <td class="border border-gray-300 px-4 py-2"><%= result['author_name']&.join(', ') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-gray-600">No results found.</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenLibraryDemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>